version: "3.9"

services:
  app:
    image: nginx
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.service=nginx"
        - "traefik.http.routers.nginx.rule=Host(`www.seudominio.com.br`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
        - "traefik.http.services.nginx.loadbalancer.server.port=80" 
        - "traefic.http.routers.nginx.tls=true"

networks:
  traefik-public:
    external: true