version: "3.8"  # Versão do Docker Compose

services:
  postgres:
    image: postgres:15.10-alpine  # Imagem do PostgreSQL
    command: [postgres, --max_connections=100]  # Comando para iniciar o PostgreSQL com 100 conexões máximas
    environment:
      - POSTGRES_PASSWORD=[sua senha]  # Senha do usuário postgres
    ports:
      - "5432:5432"  # Mapeamento da porta do PostgreSQL
    networks:
      - postgres-network  # Rede do PostgreSQL
      - traefik-public  # Rede pública do Traefik
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistência dos dados do PostgreSQL
    deploy:
      mode: replicated  # Modo de replicação
      replicas: 1  # Número de réplicas
      placement:
        constraints:
          - node.role == manager  # Restrições de colocação
      resources:
        limits:
          cpus: "1"  # Limite de CPU
          memory: 2048M  # Limite de memória
    restart: always  # Política de reinício
    logging:
      driver: "json-file"  # Driver de log
      options:
        max-size: "10m"  # Tamanho máximo do arquivo de log
        max-file: "3"  # Número máximo de arquivos de log

  pgadmin:
    image: dpage/pgadmin4:6.15  # Imagem do pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: [seu email]  # Email padrão do pgAdmin
      PGADMIN_DEFAULT_PASSWORD: [sua senha]  # Senha padrão do pgAdmin
    ports:
      - "5050:80"  # Mapeamento da porta do pgAdmin
    networks:
      - postgres-network  # Rede do PostgreSQL
      - traefik-public  # Rede pública do Traefik
    deploy:
      mode: replicated  # Modo de replicação
      replicas: 1  # Número de réplicas
      placement:
        constraints:
          - node.role == manager  # Restrições de colocação
      labels:
        - "traefik.enable=true"  # Habilitar Traefik
        - "traefik.http.routers.pgadmin.service=pgadmin"  # Serviço do Traefik para pgAdmin
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.seudominio.com.br`)"  # Regra de roteamento do Traefik
        - "traefik.http.routers.pgadmin.entrypoints=websecure"  # Ponto de entrada seguro do Traefik
        - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"  # Resolvedor de certificado TLS do Let's Encrypt
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"  # Porta do servidor de balanceamento de carga do pgAdmin
        - "traefic.http.routers.pgadmin.tls=true"  # Habilitar TLS para o pgAdmin

volumes:
  postgres_data:
    external: true  # Volume externo para persistência dos dados do PostgreSQL

networks:
  postgres-network:
    external: true  # Rede externa do PostgreSQL
  traefik-public:
    # Rede pública do Traefik